version: '3'
services:
  postgres_funding:
    image: postgres
    container_name: postgres
    restart: always
    networks:
      - funding_network
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pwd
      POSTGRES_DB: funding_prod
    volumes:
      - B:/Projects/funding-search-engine/postgres:/var/lib/postgresql/data

  solr:
    image: solr:9.6.0
    container_name: solr
    restart: always
    networks:
      - funding_network
    ports:
      - "8983:8983"
    volumes:
      - B:/Projects/funding-search-engine/solr/data:/var/solr

  funding_search_engine:
    image: jeniustech/funding-search-engine:0.0.92
    container_name: funding_search_engine
    restart: always
    networks:
      - funding_network
    ports:
      - "8080:8080"
    volumes:
      - B:/Projects/funding-search-engine/scrape_data:/var/scrape_data
    depends_on:
      - postgres_funding
      - solr
    environment:
      - PORT=8080
      - FLYWAY_ENABLED=true
      - DB_URL=jdbc:postgresql://postgres_funding:5432/funding_prod
      - DB_USER=admin
      - DB_PASSWORD=pwd
      - DB_POOL_SIZE=50
      - SOLR_URL=http://solr:8983/solr

      - KEYCLOAK_CERTS_URI=https://auth.innovilyse.com/auth/realms/innovilyse/protocol/openid-connect/certs
      - KEYCLOAK_URL=https://auth.innovilyse.com/auth
      - KEYCLOAK_REALM=master
      - KEYCLOAK_SERVICE_REALM=innovilyse
      - KEYCLOAK_CLIENT_ID=admin-cli
      - KEYCLOAK_USERNAME=admin
      - KEYCLOAK_PASSWORD=Beqwo#@!8yrn%b89p0QW
      - FACEBOOK_CLIENT_ID=707848977926943
      - FACEBOOK_CLIENT_SECRET=d1c7575b85e636b0e2aee3c4526aa9fd
      - GOOGLE_CLIENT_ID=242445727745-89ep6gf9vcts9v9bprbar2g9kc2dphbp.apps.googleusercontent.com
      - GOOGLE_CLIENT_SECRET=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
      - SPRING_PROFILES_ACTIVE=prod

      - STRIPE_API_KEY=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
      - STRIPE_WEBHOOK_SECRET=whsec_obpppCjQ3xV1CTLw06yVZ5D6MaAuxMvu
      - SCRAPER_DIRECTORY=/var/scrape_data
      - UI_URL=https://app.innovilyse.com

      - MAIL_HOST=smtp.hostinger.com
      - MAIL_PORT=465
      - MAIL_USERNAME=contact@innovilyse.com
      - MAIL_PASSWORD=B+R5c3EXjXep7Kd

networks:
  funding_network:

volumes:
  solr_data:
