version: '3.8'

services:
  postgres_funding:
    image: postgres
    container_name: postgres_funding
    restart: always
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pwd
      POSTGRES_DB: funding_prod
    volumes:
      - /var/data/db_funding_search_engine:/var/lib/postgresql/data
