version: '3'
services:
  funding_search_engine_test:
    image: jeniustech/funding-search-engine:0.0.9
    container_name: funding_search_engine_test
    restart: always
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - FLYWAY_ENABLED=true
      - DB_URL=jdbc:postgresql://45.133.178.241:5432/funding_prod
      - DB_USER=admin
      - DB_PASSWORD=nm[pv3[0%&#{!td745@#
      - DB_POOL_SIZE=50
      - SOLR_URL=http://45.133.178.241:8983/solr

      - KEYCLOAK_CERTS_URI=https://auth.innovilyse.com/auth/realms/innovilyse/protocol/openid-connect/certs
      - KEYCLOAK_URL=https://auth.innovilyse.com/auth
      - KEYCLOAK_REALM=master
      - KEYCLOAK_SERVICE_REALM=innovilyse
      - KEYCLOAK_CLIENT_ID=admin-cli
      - KEYCLOAK_USERNAME=admin
      - KEYCLOAK_PASSWORD=Beqwo#@!8yrn%b89p0QW
      - FACEBOOK_CLIENT_ID=707848977926943
      - FACEBOOK_CLIENT_SECRET=d1c7575b85e636b0e2aee3c4526aa9fd
      - GOOGLE_CLIENT_ID=242445727745-89ep6gf9vcts9v9bprbar2g9kc2dphbp.apps.googleusercontent.com
      - GOOGLE_CLIENT_SECRET=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
      - SPRING_PROFILES_ACTIVE=prod

      - STRIPE_API_KEY=sk_test_51PUU4UL9MMMwitwgjRvYpFKvbSg7udQJqnvUtMmkNCdUY3gdyu8I9VzIsywzgnPPiPFgd4CJ37byoGzEGTBmZR8T00Mr70QbB3
      - STRIPE_WEBHOOK_SECRET=whsec_idc011mZ5f6L468DPgYf5uYShhJ80jtq
