version: '3'
services:

  keycloak_db:
    container_name: keycloak_db
    restart: always
    ports:
      - 5433:5432
    image: postgres
    volumes:
      - /var/data/db_keycloak/:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=innovilyse_auth
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=opmi4$^$&v29-04v90V43208#78N0NU
      - POSTGRES_MAX_CONNECTIONS=100

  innovilyse_auth:
    image: jeniustech/keycloak:latest
    container_name: innovilyse_auth
    restart: always
    ports:
      - 8180:8080
    volumes:
      - /etc/letsencrypt/archive/auth.innovilyse.com:/etc/ssl
      - /home/docker_files/keycloak/theme/custom:/opt/jboss/keycloak/themes/custom
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=Beqwo#@!8yrn%b89p0QW
      - KEYCLOAK_FRONTEND_URL=https://auth.innovilyse.com/auth

      - DB_VENDOR=postgres
      - DB_ADDR=keycloak_db
      - DB_DATABASE=innovilyse_auth
      - DB_USER=admin
      - DB_PASSWORD=opmi4$^$&v29-04v90V43208#78N0NU
      - DB_SCHEMA=public
      - DB_MAX_POOL_SIZE=50
    depends_on:
      - keycloak_db
