version: '3.8'

services:
  solr:
    image: solr:9.6.0
    container_name: solr
    ports:
      - "8983:8983"
    volumes:
      - B:/Projects/funding-search-engine/solr/data:/var/solr

volumes:
  solr_data:
