version: '3.8'
services:
  solr:
    image: solr:9.6.0
    container_name: solr
    restart: always
    ports:
      - "8983:8983"
    volumes:
      - /var/data/data_solr:/var/solr
volumes:
  solr_data:
